### ISSUE TITLE
There is no link back to the collection from its About page

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#145]
There should be a link on the page, preferably under the collection name.

**Comment by ben3000** [comment]
For some reason accessing the About page also opens a new window/tab. I feel this is unnecessary.

**Comment by m-r-c** [comment]
There is no link from the About page to the collection because the intent was that you just close the tab - this avoids any questions of where you want to go back to (do you go back to the collection home page, or back to the profile you were viewing, etc).

The idea was that the main navigation flow (between collections and profiles) keeps you in the same tab, but any ancillary pages like About and Glossary, and links to external systems like KeyBase, Biocache etc would open a new tab.

This sort of thing is fairly subjective, of course, but that was the original idea.

**Comment by ben3000** [comment]
I usually cast the net a bit wider for what to keep in one tab, namely any page that forms part of the application, including ancillary pages. Links outward to external systems I agree feel OK done as new tabs.
