### ISSUE TITLE
Profile revision history has blank changes in it

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#177]
E.g. see Eremophila forrestii subsp. forrestii in profiles-dev

**Comment by chrisala** [comment]
The main causes of this appear to be:
1) You can press save on many content sections without actually making a change.  This appears to be the cause of the blanks in the referenced profile.  (Specifically the images).
2) Changes to the privateImages field are not compared/displayed.

Options are:
1) Detect a save without a change when doing audit logging (tricky in part because of #267).
2) Only allow save to be pressed on dirty form sections (angular default dirty detection just flags the form has been interacted with so you can undo an edit and still have the form marked dirty so this won't fully eliminate empty audit messages).
3) Filter out entries on the view that will result in an empty display (possible performance issues).

**Comment by pwscsiro** [comment]
My 2 cents : I vote for option 2, on the general principle that ui components should be disabled (if they aren't currently usable) but visible (so the user knows they can be available) and ,at the risk of exposing my ignorance of the technology stack, wonder whether the back end validation can check that the view validation hasn't missed something to cater for the mentioned edge case.

**Comment by chrisala** [comment]
I've done the following:
1. Disabled the save button on form sections when the form is not $dirty.  Note that this will not prevent saves of unchanged data as the angular $dirty gets flagged after the form has been interacted with, even if the changes are subsequently undone.
2. Added diffs for staged images.
3. Filtered audit data such that comparisons that would not produce a difference are not displayed.  Added pagination to the list to support this (so that processing is not done on every item of a potentially very large list).

**Comment by chrisala** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-28
