### ISSUE TITLE
AVH doesn’t seem to restrict information access for threatened species

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#220]
\4. MAPPING

**Comment by m-r-c** [comment]
Can SDS interaction be included in the ALA Map plugin? 

Also check with Biocollect, since it had the same requirement (and uses the map plugin, too).

**Comment by m-r-c** [comment]
AVH/Biocache does this by default, but on a per-species basis. We'll need specific examples of species which are not being dealt with.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
Distribution for threatened species needs to be obfuscated as per the SDS. Needs to apply in UI and in .pdf.
May be because those doing testing have high level access so are getting the unrestricted view. Even if you have legitimate unrestricted access the .pdf you generate must be restricted. Therefore the UI for everyone needs to be restricted.
Michael to confirm this is an issue and document further.

**Comment by m-hope** [comment]
Initial investigation shows that the SDS data is being brought across to the eFlora correctly (ie: it is generalised) despite my account being an Admin (ie: I have "Club View" in AVH).  This is true for both the web display and PDF (although the pdf resolution is so poor it doesn't seem to matter).  This was done using Acacia Filifolia...

Interestingly when I tried Ficus lilliputiana, only 6 records were marked as generalised in AVH, most likely due to name matching issues (ie: subspecies haven't specifically been listed in the Sensitive lists and therefore not generalised)... These subspecies records have therefore been brought across into eFlora as non-generalised.  This might be the source of the original issue, in which case this is a ALA/AVH/SDS issue and not specific to Profiles.

Until a specific example is available where generalised data in AVH is coming into eFlora as non-generalised, I suggest we park this issue.

**Comment by RobinaSanderson** [comment]
Issue will be closed unless we can find an example.
