### ISSUE TITLE
search doesn't work in Internet Explorer v 9.0.8112.16421 OK in chrome and firefox

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#24]
http://www.bugherd.com/projects/58735/tasks/13

**Comment by ben3000** [comment]
It doesn't work in Chrome (40) or Firefox (35 or 38) for me, and I see a CORS error on the Firefox console when attempting to edit a profile too: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://aaa.bbb.ccc.ddd:8080/profile-service/profile/a1422b8b-dccc-4942-ac02-780adefbea64. This can be fixed by moving the resource to the same domain or enabling CORS."

**Comment by ala-bugherd** [comment]
Please retest. There were some issues with IE 9 that have now been resolved. 

It is important to note that the site does NOT work in Compatibility Mode. IE 8 and below, including IE 9 Compatibility View (which makes IE9 behave more like IE8) are not supported.

**Comment by ala-bugherd** [comment]
Thanks for your message. I will be out of the office on 24 April and in meetings with only intermittent email contact 27-30 April.
