### ISSUE TITLE
Add an 'unknown' category to the browse page` 

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#247]
The Browse tab will only include profiles with a matched name, because the classification hierarchy is derived from the match. This means profiles without a matched name cannot be found using the browse feature

Adding an 'Unknown' category will fix this.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-3

**Comment by KevinThiele** [comment]
Simply collecting all unmatched profiles under an "Unknown" category will be suboptimal. For example, of someone creates a profile for a new, un-named species of Acacia (e.g. a phrase-named species that has not yet been included on APNI/APC), well we know that this is a species of Acacia, and hence it belongs in the family Fabaceae etc. Is there a way to capture taxonomic knowledge of the unmatched profile rather than assume nothing. Note that there should be no cases where an unmatched profile doesn't fit the taxonomy at all (e.g. a "Bob" profile)

**Comment by m-r-c** [comment]
The purpose of this task was purely to ensure that all active profiles were discoverable via the Browse feature. Unlike the other categories, if there are no entries in the 'unknown' category then it will not be visible.

Allowing Editors to specify the taxonomic hierarchy for profiles with an unmatched name is something that we should consider under the broader name issues. I have created a task to serve as a reminder when we get to that stage (#258 on the backlog).
