### ISSUE TITLE
Admin control re-index ES not working

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#261]
Manually invoking from a REST client does.

**Comment by pwscsiro** [comment]
In order to make the most recent data available
as an Admin
I want to be able to manually trigger a full re-index of the collection

**Comment by pwscsiro** [comment]
Login as admin, choose User settings, Admin, click rebuild search index.

![reindexsearchindexscreenshot](https://cloud.githubusercontent.com/assets/17239936/13479914/77898f14-e12e-11e5-914b-c09408ca97e2.png)

**Comment by pwscsiro** [comment]
Notes to self: The error is intermittent and seems to live in HUB, as the re-index is being done on the Service side regardless of whether an error is thrown on the client side. So I'm trying 2 things: a  null test on the response in case we are accidentally masking other errors and secondly applying the web services default timeout in case its related to response time. I haven't been able to remove a Malformed Url exception - I think this is because of the port number using localhost.  I've previously used plugins for sending rest calls which work quite well, although the syntax can be a bit obtuse although concise. Also used Restlet plugin as per [https://automagical2012.wordpress.com/2014/05/01/grails-2-post-complex-data-using-restlet/](url). Don't like Restlet but the plugin is surprisingly elegant.

**Comment by pwscsiro** [comment]
Application of optimistic locking exposed an issue with Status save, changed code around to accommodate
