### ISSUE TITLE
Images not appearing by default for Acacia acinacea, biocache data not returning

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/profile-hub#270]
1. No images are appearing for Acacia acinacea.

2. When running locally, logged in and in edit mode with Admin access when I try to create a new snapshot, profile-hub is generating the following error:
NullPointerException at au.org.ala.profile.hub.ImageService.retrieveImages(ImageService.groovy:181).

The biocacheImages list is null following a call to the biocache service:
Fetching data from http://biocache.ala.org.au/ws/occurrences/search.json?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aapni.taxon%3A295874+AND+%28data_resource_uid%3A%29&fq=multimedia:Image&format=json&im=true

However the images are available when searched manually in the Biocache interface.

**Comment by m-r-c** [comment]
The problem was when there are no approved image sources. The export service was not including the collection's data resource id in the list of image sources when calling biocache, so it ended up passing an empty string. All collections have their own data resource id, so it should always be included in the biocache call.
