### ISSUE TITLE
Test profile pages for mobile compatibility

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#403]

**Comment by RobinaSanderson** [comment]
Robina and Michael will try to do this before the sprint starts. 

If there are issues, ALA will need to look a contracting in appropriate skills to resolve.

**Comment by RobinaSanderson** [comment]
In chrome, can put into mobile view
Developer tools 
Responsive view mode
Options for various devices

**Comment by ben3000** [comment]
### Profile Public view

- The close button on the taxonomy item in the left sidebar scrolls off the right side of the screen for all available smartphones configured in Chrome's responsive view -- this should instead slide in to a maximum of 100% of the window's width.
- The way the list of matching taxa loads on the Browse tab provides very little visual indication that anything occurred when you click on a genus under the Genus category.
- The map that is displayed on the Distribution tab is very tall -- 1.5 times the height of a smartphone's screen even when the displayed points are all concentrated on a small area near Perth. The width of the map is good, as there is room to either side to swipe the page up and down.
- The options provided under the Distribution map display with poor wrapping because it has been styled using a set of span elements instead of using a responsive inline-list.
- The "View image details" link under an image in the Gallery tab puts up a modal that scrolls off the bottom of the screen; and, as the image is embedded in a leaflet.js frame, the user will need to swipe from underneath the leaflet frame to make the modal scroll; making the modal fit around the bounds of the image should reduce the space taken up by the modal.
- The Options button dropdown menu scrolls off the right-hand side of the screen; adding a .dropdown-menu-right to this menu fixes the problem at smartphone sizes, but causes another display issue at large sizes; this is also true in profile edit mode.
- The right-alignment on the "Last updated" text should be removed for smartphones, as it wraps for these, and thus looks a bit odd
- The "scroll to top" text scrolls underneath the ALA icon near the bottom of the page and has the same colour as some of the text on the page; check the z-index definitions on these properties.
- At smartphone sizes, the existence of the buttons for the sidebar make the page look mis-aligned because the margin/padding is different on the left-hand side; could this be a swipe-in feature to reclaim the space for the content?

**Comment by ben3000** [comment]
### Opus Search tab

- The size of the search button bar leaves almost no room for the search text.

**Comment by ben3000** [comment]
### Opus Browse tab

- The way the list of matching taxa loads on the Browse tab provides very little visual indication that anything occurred when you click on a genus under the Genus category.
- The category sidebar needs to be more compact on smartphones as it takes up too much room on the screen

**Comment by m-hope** [comment]
@RobinaSanderson - we need to consider if/how to fix these... will need individual stories for each issue.

**Comment by RobinaSanderson** [comment]
Stories have been created for the identified issues.
