### ISSUE TITLE
can't specify hierarchy on an existing profile

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#409]
On a created profile, if you click on 'Edit name' you have the option to remove the matched name... once you do this and rename to an unrecognised name, you will get the option to "Specify hierarchy for..." the new profile, but clicking on this link doesn't bring up the part where you can actually specify the hierarchy.

Ie: you get this:
![image](https://cloud.githubusercontent.com/assets/8856025/18156176/acbce588-7057-11e6-875a-38a279a25b0d.png)

instead of this (which is what you see when you create a new profile):
![image](https://cloud.githubusercontent.com/assets/8856025/18156143/728a0e7c-7057-11e6-937a-824472bf34bd.png)

**Comment by RobinaSanderson** [comment]
Test whether this is still an issue.

**Comment by RobinaSanderson** [comment]
There now appears to be an option to specify heirarchy:

![image](https://cloud.githubusercontent.com/assets/23368496/22633809/b14f3c0c-ec78-11e6-966f-ea5601ddb684.png)

Clicking on the option gives the following:
![image](https://cloud.githubusercontent.com/assets/23368496/22633823/cf6114d6-ec78-11e6-9042-bfdbcb9f38ad.png)

@m-hope  could you please comment as to whether this is expected behaviour?

**Comment by m-hope** [comment]
Can confirm that this is still not the expected behaviour... clicking on the Specify Hierarchy button should allow the editor to specify the rank (and then parent taxa) for the profile (at the moment it just toggles between Clear hierarchy and Specify hierarchy).

Interestingly, if a profile has had its hierarchy manually specified when it was created, the 'Specify hierarchy'  button works appropriately (ie: you can clear the hierarchy, then specify a new hierarchy correctly)... this bug only occurs when a profile is not placed in a hierarchy when the profile is created...
Unfortunately, while we could enforce a workaround via workflow that ensures that all profiles are manually placed in a hierarchy at time of creation (even if it a temporary one which can be changed later), this will not help the case for all imported profiles (where the script won't do this)..., Given the quantity of profiles we are going to import and the reasonably high number of unmatched profiles in the Import test, I suspect this bug will need to be fixed prior to release (and early on, so that editors will have the time to manually place unmatched imported profiles).

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-163

**Comment by RobinaSanderson** [comment]
Tested by:
* in profiles-dev: ALA test collection, opened profile for Leptomeria obovata
* selected edit
* selected edit name
* clicked button to unmatch name
* dialogue box opened asking if I really wanted to unmatch name, selected OK
* profile was unmatched with no option to place in hierarchy, I can match to another name but not place this one in a hierarchy

test 2:
* Created new profile dysoxylum fred
* didn't match name
* placed as a species under dysoxylum
* selected edit name
* selected check name
* selected specify hierarchy
* was able to place as a species under acacia 

Hi @m-hope  - specifying the hierarchy for a new profile works, but you are unable to specify the hierarchy for a profile that was previously matched. Is this expected behaviour?

**Comment by RobinaSanderson** [comment]
After discussion with Michael the expected behaviour is:
Once a profile has been matched, you are able to change the match to another concept but you are not able to unmatch the profile and manually specify where it should sit.

The system supports this so the issue is complete.
