### ISSUE TITLE
Name Search - Change search results so that when the APC Concept name is entered only profiles that mach the APC concept are displayed in search results

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#510]
As a searcher in a collection
I want search results in the name search simplified
So that I am not confused by synonyms and misapplied names

Prerequisites
1. the user has navigated to the search page
2. they have selected name search
3. they have selected the search option to include NSL names
4. they enter a name

Requirements
1. If the name entered matches a profile (an entry in the master list), the profile is displayed in search results.
2. If the name entered is a synonym of an APC accepted name, and a profile exists for the APC concept, the profile is displayed in search results.
3. If they have selected to display archived profiles and the name matches an Archived profile, it is displayed in the search results
4.  If they have selected to display archived profiles, and if the name entered is a synonym of an APC accepted name, and an archived profile exists for the APC concept, the profile is displayed in search results.
5. Any other relationships are ignored and do not display in search results.

see table under "Search Results" heading for analysis: https://confluence.csiro.au/display/ALAEP/eFlora+name+matching 
Note: table has been updated 28/04/2017 this should now be complete

**Comment by RobinaSanderson** [comment]
Link to current story around showing NSL reasons.
Check if other tasks will be effected by this story.

Can live with current behaviour if several days work.

**Comment by m-hope** [comment]
The JSON output from NSL provides three parts: 
•	a “synonyms” section that provides accepted names where the search term is a {synonym, misapplication, etc};
•	an “acceptedNames” section which provides the full accepted scientificName for the search term (if there is one);
•	a “synonyms” sub-section to the acceptedNames section providing all names that are {synonyms, misapplications, etc} of that accepted name.

Currently we’re including all names found in this last section, which is why we seem to be ‘traversing the name tree backwards’ (for want of a better term) in our search results.  We should now be completely ignoring any names that appear in that last sub-section for our search results and not including them in the list of names to search the profile database (or masterlist if implemented).

**Comment by RobinaSanderson** [comment]
This issue has been resolved as part of #380
