### ISSUE TITLE
UI - Search enhancements

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#530]
As a search user 
I want consistent search options in both the header search selection and the search page 
So that I can access search functionlaity from both the menu header and the search page

Business requirements:
- For both menu bar search and search page, create three search types (issues #528 and #530):
        - By Scientific Name (as per the current name search without alternate names)
        - By Common Name (as per the current name search with alternate names option on)
        - Containing Text (as per the current text search)
 - Implement hide stubs option (issue #483) which will be an option available for all search types
 - Implement/keep the 'Must contain all items' option for text searches and remove all others (issues #530, #new)
 - Investigate the ability for option settings to persist within a browse session (currently don't) and across both the menu bar search and the search page (ie: if set on one, will be set for the other).
 - Change the search and trash buttons on the search page to a single magnifying glass icon (issue #541). 

This issue brings together and supersedes the requirements in issues:
#528 
#483 
#530
#541

Note: further discussions on this issue now mean that the Menu Search bar will no longer have the ability to set the options for searches... the only way to set these options will be through the Search Page (which should be always visible when the search results are displayed).  This means the previous requirement to have a drop down menu on the Menu Search Bar (on the right hand side with a cog symbol) is no longer necessary.

**Comment by m-hope** [comment]
Note that issues #483 and #471 create new search options that need to be considered and handled in this issue.

**Comment by RobinaSanderson** [comment]
Hi @m-hope and @temi 
I've updated this issue to include the search requirements discussed on Friday. I will close the issues that are not in progress, except this one. I can close the ones in progress as long as that doesn't affect anything else (are code edits associated with the stories?)
Michael, if you want to add more explanation to the search work, this should be the story to progress with.

**Comment by RobinaSanderson** [comment]
@temi - could you please provide a revised estimate for this work? The original stories added up to 4 days but this story now includes further changes.

**Comment by KevinThiele** [comment]
I'm keen to know which parts of this are likely to be most difficult, so we can explore simpler options to save time. For example, we could consider having all stubs as non-published for this release, so we don't need to worry about them in this issue, if that bit's hard?

**Comment by KevinThiele** [comment]
So here's an idea - we can remove the need to option the search completely - so all we'll have is a simple drop-down box to specify the search type. Let's say we remove the need to option stubs on and off in the search result. We're left with four optioning requirements:
"Implement hide stubs option (issue #483) which will be an option available for all search types
Implement/keep the 'Must contain all items' option for text searches and remove all others (issues #530, #new)
Investigate the ability for option settings to persist within a browse session (currently don't) and across both the menu bar search and the search page (ie: if set on one, will be set for the other)."

We could fix all these if the dropdown contains the following items.

- By Scientific Name [as per the current name search without alternate names]
- By Common Name [as per the current name search with alternate names option on]
----------------------- [separator]
- With all words [returns profiles matching word1 AND word2...]
- With any word [returns profiles matching word1 OR word2...]
- With phrase [returns profiles matching "word1 word2..."]

Note that the last one is new - I include it because it makes sense - it' essentially a one-word search term where the "word" to search for is the phrase. As a new requirement, this could be dropped if too hard to deal with the whitespace.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-171

**Comment by m-hope** [comment]
Happy that all criteria (except for icons on Search page) have been met.   Have reopened #541 to look at changing the Search page icons as part of the mobile compatibility functionality in the future.

**Comment by temi** [comment]
I does change for me. An example from profiles-dev is given below.
![image](https://user-images.githubusercontent.com/1152259/27845615-21aa32de-6174-11e7-868b-ff0e18b7864b.png)

**Comment by m-hope** [comment]
??? this is what I see:
![image](https://user-images.githubusercontent.com/8856025/27845827-e29b9342-6175-11e7-97f1-ae199794f8c3.png)

**Comment by m-hope** [comment]
Can confirm that the magnifying search icon on the Search page only appears if the window is narrow (ie: in mobile configuration)... my apologies to Temi!!!
