### ISSUE TITLE
Search function not working in Profiles-dev

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#583]
The search function doesn't return any results on Profiles-dev, regardless of the search term (including a blank search) or the search type.  This function is working correctly on the production environment.

I can't see anything in the logs on profiles-dev to indicate what is going on... IE: after the initial search request to profiles-service (2017-10-03 11:45:08,776 DEBUG [SearchService] Searching for acalypha in collection(s) [foa] with options au.org.ala.profile.util.SearchOptions(true, true, false, true, true, false, true)), the log is empty... where as on production, you see calls to the ALA Name service, BIE, etc.

**Comment by javier-molina** [comment]
@m-hope 

search is working for me, it just take a while for the results to come back, the only visual indication is the thin horizontal bar at the top.

Would it be sensible to increase the height of the bar or show a prominent spinner instead of/in addition to the bar?

Please let me know what's your preference.

![screen shot 2017-10-03 at 3 34 18 pm](https://user-images.githubusercontent.com/8326394/31110139-9c4293e2-a850-11e7-9f09-794c1f30ed20.png)

**Comment by javier-molina** [comment]
After discussing this with Michael, there is no more work required on this ticket at this stage.
