### ISSUE TITLE
Profiles: missing map filters

### ISSUE THREAD

**Issue by zoeknapp** [AtlasOfLivingAustralia/profile-hub#666]
Some of the map filters are missing, e.g. location (and all sub-filters), which is a key filter set for the Flora of Australia

**Comment by sbearcsiro** [comment]
This change reduces the total number of facets requested from the biocache occurrence search from 67 to 20 due to a hard limit of 32 facets imposed by the service.

**Comment by sbearcsiro** [comment]
The occurrence map is powered by the ALA biocache occurrence search.  Biocache imposes a limit of 32 facets on an occurrence search.  Previously we were attempting to get results for 67 facets.  This meant our list of facets was truncated at 32 items, which is why facet groups such as Location and Record didn't show up.  By limiting the total number of facets requested the Location facets will always show up (if available).  You can see the removed facets by clicking on the code change linked to this issue, note the the facets in the .json file have internal identifiers that are not necessarily the same as the UI labels.  Also note that any facet result that only has 1 value is hidden in the UI.

**Comment by RobinaSanderson** [comment]
Tested by checking https://aws-profiles.ala.org.au/opus/alatest/profile/Acaciella%20glauca

The IBRA regions and Sub regions (identified as important filters for the ABRS) are now available. I was able to apply an IBRA region as a filter. I saved the change and opened the public view. The change to the map was still visible.

**Comment by peri-bolton-abrs** [comment]
This issue needs to be followed up further. Although we now have access to the location filters, there are still filters that we had access to at the beginning of 2018 that we cannot access now. Some of these ABRS views as critical to the delivery of an authoritative Flora.

Below is a list of all the filters that were available in 2018. Asterisks are those that we believe to be critical.  Some of these, including institution we forsee to be important for regional floras that want to base their collections on particular herbaria. 

I think it would also be helpful if someone could clarify why the filters are now being truncated on the biocache when they weren't previously (beginning of 2018)?
### 
List of filters at the start of 2018.

**Taxon**
Taxon name (processed) 
*Taxon name (provided) 
 Kingdom
 Phylum
 Class
 Order
 Family
 Genus
 Species
 Infraspecific taxon
 Identified to rank
 Name match metric
 Botanical group
 Common name (processed)
 Species subgroups
 Species interaction
 State conservation status
 State conservation status (unprocessed)
 EPBC conservation status
 EPBC conservation status (unprocessed)
 
 
 
**Identification**
 Identified by
 Identification qualifier
 Provided name issue
 Specimen type
 Original name usage
 
 
 
**Occurrence**
*Collector
*Life Stage
******Establishment Means (This one is the most critical of the filters that we can still not access, because it allows us to remove cultivated records).
Month
*Year
*Year By Decade
Multimedia
 
**Location**
 *Country
 *States including coastal waters
 *Elevation
 Minimum elevation (in metres)
 *AUS Local gov. area
 *IBRA 7 Regions (We are pleased the IBRA regions are available again).
 *IBRA 7 Subregions
 IMCRA 4 Regions
 IMCRA Meso-scale Bioregions
 NZ ecological districts
 NZ land districts
 NZ provinces
 National Dynamic Land Cover
 Vegetation types - pre-1750
 Vegetation types - extant
 *Commonwealth Electoral Boundaries
 NRM Regions
 Ecoregion
 Uncertainty (in metres)
 Coordinate uncertainty (in metres)
 Spatial validity
 Location ID
 
 
**Record**
*Record type
 Multimedia
 Presence/Absence
 
**Assertions**
Sensitive data
 Record issues
 Outlier for layer
 Outlier layer count
 Has annotations
 Annotations by user
 Asserted duplicates
 Asserted duplicate type
 
**Attribution**
 *Herbarium 
 *Institution
 
**Misc**
Datum

**Comment by RobinaSanderson** [comment]
IBRA regions are now available in Production. I am closing this issue and will create a new issue with the filters documented 16 April 2019
