### ISSUE TITLE
Snapshot (version) function no longer working

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#672]
When you lock a profile for editing and then ‘publish draft changes’ it asks whether you would like to publish a snapshot version. If the user selects ‘yes’ to the snapshot, the profile saves the new changes but does not create the snapshot version (which should appear in the Version section of the profile).

Similarly, manually created snapshots don't create anything.

In both cases one or two "An error occurred during the snapshot process" errors are displayed.

**Comment by temi** [comment]
There were a couple of problems with snapshot creation.
1. Snapshot was failing for profiles with no author. ANDS service mandates author name. It was decided snapshot should fail if author name is not provided. An appropriate error message was added. Also, regex to find author field was modified to match words like "Author", "Author(s)" i.e. anything containing "author" string.
2. Snapshots created on draft profile were overwritten during publication. This was because publications attribute in public and draft profile were not in sync. It was decided to have publications attribute only in profile domain object. Therefore, removed publications attribute in draft domain object.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-214
