### ISSUE TITLE
Setting primary image prevents further updates to profile

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#739]
Steps to reproduce - 
1. Set a primary image on a profile, save image settings.
2. Edit an attribute and save. Profiles throws an error.

Profile domain object fails `primaryImage` validation. This is likely due to `enum` check.

**Comment by m-hope** [comment]
Strangely only seems to effect some collections (specifically the SE Arnham Land collection, eg: https://profiles-dev.ala.org.au/opus/896e4aa1-72a7-46d9-beb3-7c30f5f96016/profile/Kwait%20Sineik)... perhaps because they exclusively use private images.  I have tried to replicate the problem in my test collection, but even adding private images and setting them as main image doesn't cause the issue (https://profiles-dev.ala.org.au/opus/michael/profile/Triglochin%20procera), .

**Comment by m-hope** [comment]
Confirmed fixed.  

Tested saving edits on profiles known to have caused problems in the past (eg: https://profiles.ala.org.au/opus/896e4aa1-72a7-46d9-beb3-7c30f5f96016/profile/Ba%CC%88pi%20(Northern%20Small-eyed%20Snake) and other profiles both on prod and dev profiles servers.  In all cases, profiles where the primary tag was set produced an error on production and completed successfully on the dev server.
